markdown: redcarpet
redcarpet:
  extensions: ["superscript","no_intra_emphasis","autolink","strikethrough"]

permalink: /blog/:title/

source: .
destination: ./_site

blog_pagination_count: 6

tag_page_layout: tag_page
tag_page_dir: tag

