url: http://www.grok-interactive.com
markdown: redcarpet
redcarpet:
  extensions: ["superscript","no_intra_emphasis","autolink","strikethrough"]

permalink: /blog/:title/

source: .
destination: ./_site

paginate: 5
paginate_path: "blog/page:num"

tag_page_layout: tag_page
tag_page_dir: tag

